### ISSUE TITLE
Melee Issues

### ISSUE THREAD

**Issue by sickjuggalo666** [meta-hub/meta_target#14]
While meta target is running i cant seem to melee but i can shoot a gun. 

https://streamable.com/mt1r2o

**Comment by Taavi-AU** [comment]
You can fix this easily by going into the client/main.lua

```lua
    DisableControlAction(0,control)
    --DisableControlAction(0,revealControl)
    DisableControlAction(0,disableControl)
```

**Comment by Senlar** [comment]
Confirmed, this works.

**Comment by meta-hub** [comment]
Resolved in latest repo
