### ISSUE TITLE
Target not clearing, can still be accessed far away

### ISSUE THREAD

**Issue by Senlar** [meta-hub/meta_target#18]
So if you target something but don't click into the menu and turn off the target... then walk away and press TAB plus click your mouse quickly you can get the interaction to still show and be usable.

Press TAB to show interaction, then let go of tab without doing anything else.
![image](https://user-images.githubusercontent.com/1503963/156841628-6a59d92d-ef35-407b-b3e8-53781423ec62.png)

Walk away, any distance you'd like...
Press TAB and QUICKLY CLICK LEFT MOUSE and you'll still have the last interaction option available.
![image](https://user-images.githubusercontent.com/1503963/156841734-0eab2f71-e076-40ad-b92e-3aed15479033.png)
You can click on it and it will still let you into the inventory or whatever it was.

**Comment by Taavi-AU** [comment]
Are you on latest update, I dont seem to have this issue, I will do some more testing, maybe I was doing wrong :)

**Comment by meta-hub** [comment]
^ As above, and also, are you taking note of the changes to the API for adding multiple models etc?

**Comment by Senlar** [comment]
Ok sorry for the delay... I just downloaded the latest update and tried this again. It seems to still be happening.
Actual location
![image](https://user-images.githubusercontent.com/1503963/160453527-81a65aef-9014-443e-aab9-48480377623c.png)

Away from the location
![image](https://user-images.githubusercontent.com/1503963/160453636-926b84d0-3de9-4d6f-a0a7-e2089a49a434.png)

It only seems to happen at first load and stops after you have actually accessed the inventory once.
https://streamable.com/hjboon

**Comment by Senlar** [comment]
https://streamable.com/loi4rb
Here's a clip of a fresh start on it showing how it happens. It also doesn't appear to be an issue with addPoint type targets so it may just be exclusive to the poly targets. I'm specifically using **exports.meta_target:addInternalBoxZone** in the videos.

**Comment by meta-hub** [comment]
This will be fixed next update, will continue to check validity of active targets regardless of NUI focus.
