### ISSUE TITLE
addModels

### ISSUE THREAD

**Issue by Taavi-AU** [meta-hub/meta_target#21]
Cant seem to use addModels on latest version, just doesnt seem to like `models`

![image](https://user-images.githubusercontent.com/97351942/159857881-ffe85218-b707-4d59-8ba3-fb730cec45e3.png)

**Comment by meta-hub** [comment]
How are you calling the function? The readme is likely outdated by now.

**Comment by Taavi-AU** [comment]
```lua
local models = {
    "prop_cs_dumpster_01a",
    "p_dumpster_t",
    "prop_snow_dumpster_01",
    "prop_dumpster_01a",
    "prop_dumpster_02a",
    "prop_dumpster_02b",
    "prop_dumpster_3a",
    "prop_dumpster_4a",
    "prop_dumpster_4b",
}

exports["meta_target"]:addModels({
    id = "dumpsters",
    title = "Dumpster",
    icon = "fas fa-dumpster",
    models = models,
    radius = 2,
    onSelect = onModFreakzsBumhole,
    items = {
        {
            name = "search_dumpster",
            label = "Search Dumpster"
        }
    }
})
```

**Comment by meta-hub** [comment]
Argument evaluation was removed, no reason to pass a table since the compatibility files allow correct arguments are passed for provided resources. Call `addModel(id,title,icon,model,radius,onSelect,items,vars,res)` instead.
