### ISSUE TITLE
meta_target entitytype options

### ISSUE THREAD

**Issue by Taavi-AU** [meta-hub/meta_target#28]
I have attempted to use the addVehicle, addPlayer, addPed and addObject and none of them seem to work, unsure why

**Comment by PhillipEis** [comment]
Same.

**Comment by Taavi-AU** [comment]
I had a look at how it returns false on the entityType and added a check and did

```lua
if entityType == 2 then
  return true
end
```

this returned true and I was able to target the vehicle but the distance was broken where I could target the vehicle and the ground, I have no idea...

**Comment by Taavi-AU** [comment]
latest PR to fix this issue...

https://github.com/meta-hub/meta_target/pull/31
