### ISSUE TITLE
meta_target

### ISSUE THREAD

**Issue by Taavi-AU** [meta-hub/meta_target#29]
Weird issue on the latest version seems to be occurring some of the time to some player and not to others, I never got it on one of my characters but got it on my second chat

I attempted to open a target and none options showed up but the eye got stuck on my screen and this error appeared, seems to do with the api function ['point']

![image](https://user-images.githubusercontent.com/97351942/163141809-047c8484-1b74-4a57-88f6-b96567216e3b.png)

**Comment by Senlar** [comment]
Same error happened to me yesterday. Was it from housing?

**Comment by Taavi-AU** [comment]
I am unsure its happening with any point I believe

**Comment by Senlar** [comment]
I think it’s the change in housing to vector 4 which is why I was asking.

**Comment by Taavi-AU** [comment]
hmm I doubt it since it was happening to a script I have which uses vector3 for the point

**Comment by Senlar** [comment]
It seems housing is sending a nil vector. I found the houses on my server this is happening with have an entrance that is for some reason sending a nil vector3 to be distance checked.

**Comment by Skattefar** [comment]
Got this issue too

**Comment by Adzeepulse** [comment]
I’ve got the exact same error when trying to use the target on the furniture at the store, it locks the target and can’t close unless restarting server or script.
