### ISSUE TITLE
no doc and also no discord where we can get info

### ISSUE THREAD

**Issue by Capy1174** [meta-hub/meta_target#32]
no doc how to change the key of interction there should option in setting keybinds to change the key of interaction by default it on TAB so many inventories have wheel or slots on tab

**Comment by Senlar** [comment]
Doc = Readme
Change Key = client.lua > find keypress section and change it to what you want

**Comment by Capy1174** [comment]
Any detailed example on how to add for model i saw the example but i notice if i use export of qtarget it give a text on top of options when u use the eye to access the menu
But what you should add any discord to provide support.. its just a suggestion coz i think this is the best system which support export of other targets also
