### ISSUE TITLE
readme missing info on default reveal hotkey

### ISSUE THREAD

**Issue by minipunch** [meta-hub/meta_target#39]
is there a hotkey to make something show up after running the code in the example?

nothing seems to show up

yes I included it in the fxmanifest

**Comment by minipunch** [comment]
lmfao oh I found it

but I had to dig through the main.lua file to find it lol

might want to include it in the readme heh

**Comment by minipunch** [comment]
fyi it is TAB for anyone else wondering

aka code 37

**Comment by Taavi-AU** [comment]
its always been TAB, I can add it into the read me

**Comment by Taavi-AU** [comment]
read me also needs to be completely redone
