### ISSUE TITLE
no way to get entity handle

### ISSUE THREAD

**Issue by minipunch** [meta-hub/meta_target#40]
is there no way to get the entity handle that you are targeting?

for the model one in particular

**Comment by minipunch** [comment]
just wondering how I can get the player ID from a mp_m_freemode_01 ped I am looking at assuming it is a real player

**Comment by Taavi-AU** [comment]
yes, its possible, return the ent through targetData

**Comment by Taavi-AU** [comment]
```lua
print(json.encode(targetData, {indent=true})) 
```
and look what it prints, I believe ent is inside it

**Comment by Taavi-AU** [comment]
```lua
local function onSelect(targetData, itemData)
  print(json.encode(targetData, {indent=true})) 
end
````

**Comment by minipunch** [comment]
Yeah I didn't see anything in `targetData`

But I did get it with:
```
 onSelect = function(a, b, entityHandle)
		if DoesEntityExist(entityHandle) then
			local serverId = GetPlayerServerId(NetworkGetPlayerIndexFromPed(entityHandle))
```

seems like the handle is passed as the last arg for me

**Comment by Taavi-AU** [comment]
ah okay so itd be passed in a different arg
