### ISSUE TITLE
no example for how to use .addVehicle

### ISSUE THREAD

**Issue by minipunch** [meta-hub/meta_target#41]
I would like to be able to use this on any vehicle model without having to explicitly define it with `.addModel`

I see there are functions for `.addVehicle` in `main.lua` but there is no example usage in the docs

Any way we can get this added?

**Comment by Taavi-AU** [comment]
without vars, res and canInteract

```lua
exports["meta_target"]:addVehicle(name, title, icon, 2.5, onSelect, {
  {
    name = "option_name",
    label = "Option Label"
  }
})
```

with vars, res and canInteract
```lua
exports["meta_target"]:addVehicle(name, title, icon, 2.5, onSelect, {
  {
    name = "option_name",
    label = "Option Label"
  }
}, {
  foo = "bar"
}, GetCurrentResourceName(), function(target,pos,ent,endPos,modelHash,isNetworked,netId,targetDist,entityType)
  return true
end)
```

**Comment by Taavi-AU** [comment]
![image](https://user-images.githubusercontent.com/97351942/213076427-4a2df6f7-52e7-42f4-a99e-142089223a0b.png)


added inside of readme

**Comment by Taavi-AU** [comment]
soon going to create a docs website or use github wiki to make all exports easier

**Comment by minipunch** [comment]
Sounds good

Also I think there is a bug in the .addVehicle code because your example didn't work until I updated it

**Comment by Taavi-AU** [comment]
what did you have to update

**Comment by minipunch** [comment]
Or maybe my `main.lua` is out of date because the code looks different than the the latest version in the repo

I can try updating and see if it works better

Mine was:

```
 ['vehicle'] = function(target,pos,ent,endPos,modelHash,isNetworked,netId,targetDist,entityType)
    if not ent
    or not entityType ~= 2 
    then
      return false
    end
```

and the issue was `or not entityType ~= 2` needed to be changed to `or entityType ~=2` (remove the extra 'not')

**Comment by Taavi-AU** [comment]
ah right, yeah give it an update, it works for me

**Comment by minipunch** [comment]
Awesome, looks like it works!

Good stuff!

**Comment by Taavi-AU** [comment]
:)
